### ISSUE TITLE
Some issues about retrain model

### ISSUE THREAD

**Issue by ghost** [utlive/niqe#1]
Hi, I want to use my images to train a new model, I run command in matlab step by step from readme.txt. But I get mu_prisparam is NaN and cov_prisparam is NaN, Can you help?
![image](https://user-images.githubusercontent.com/78402904/130576618-1fd6cf0c-4e09-4540-9199-fce585a769cf.png)

**Comment by JoshuaEbenezer** [comment]
Hi @qilonghai. NIQE is a blind algorithm and is not meant to be retrained. Retraining for NIQE is only in the context of training its modeling of pristine images.  You have to ensure that the images you have are free of distortion. In addition to that, I'm not sure why NaNs would ever occur, but the original code has provisioned for that by taking the nanmean of the parameters.
