### ISSUE TITLE
Greyscale mode: niqe

### ISSUE THREAD

**Issue by vsantjr** [utlive/niqe#3]
Hello,
Congrats for the version of the metrics in python. About niqe, do we need to read the images in greyscale? Because we see this in the code:

```
def niqe(img):
    blocksizerow = 96
    blocksizecol = 96
    h, w = img.shape # Here, the number of channels is not considered.
```
Thus, in order to work, I had to read the image (openCV) in greyscale:

```
image = cv2.imread(image,0) #Greyscale
h, w = image.shape
print('H: {} - W: {} - Number of dimensions: {}'.format(h, w, len(np.shape(image))))
```
Note that if we consider the 3 bands (RGB), there is an assertion error:

```

  File ".../live_python_qa-main/utils.py", line 55, in compute_image_mscn_transform
    assert len(np.shape(image)) == 2
```

Moreover, the value of the metric is the `quality` variable of the niqe function. Right?

Thank you.

**Comment by JoshuaEbenezer** [comment]
Hi @vsantjr . Thanks for your interest in NIQE. You're right, NIQE is a luma-based model only. You have to convert the image to grayscale to use NIQE.
And yes, the value of the metric is the `quality` variable in the function.

**Comment by vsantjr** [comment]
Thank you Joshua for your reply.

Best Regards.

**Comment by vsantjr** [comment]
Hello,
One more doubt. These are the default values of blocksizerow = 96  and blocksizecol = 96. As for my images with 128 x 128 dimension/resolution it did not work since SVD does not converge. But, decreasing the size of the blocks, it does work. But, as far as I saw, as lower the block size lower the NIQE. Do you have a suggestion of "optimal" block sizes for the resolutions below?

- 128 x 128
- 256 x 256
- 1024 x 1024

Thank you again.

**Comment by JoshuaEbenezer** [comment]
Hi @vsantjr , NIQE is a completely blind algorithm that is not meant to be trained. It's meant to be deployed as-is because it has been pre-trained on a corpus of pristine natural images. If you would like to retrain it for blind deployment, then you would have to figure out the best parameters for your dataset/corpus yourself, since it will depend on the data. 

Regards,
Josh

**Comment by vsantjr** [comment]
Thank you for your explanation @JoshuaEbenezer.

Best regards.
